### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by diego-rapoport** [TBS1996/flash-tui#1]
How do I install it? Will it be available through cargo or pacman?

**Comment by TBS1996** [comment]
I'll upload it to various linux package managers once i figured out what name i wanna give to this program!

but until then, you should do the following:  

- install git and rust if you havent already
- in your terminal, go to where you wanna save the program
- paste in "git clone https://github.com/TBS1996/flash-tui"
- in the flash-tui folder, enter "cargo run" in your terminal and it should download all the dependencies and start 


let me know if this works!

**Comment by diego-rapoport** [comment]
Yes, it worked as expected!

**Comment by TBS1996** [comment]
Great! If you have any more feedback then let me know :)
